Fix Notification & Update Auth method
jellyfin/jellyfin-plugin-pushbullet pull request #7
Opened 2020-02-19 14:48 UTC by crobibero

Fixes #5

2020-04-20 06:50 UTC, matda59 commented
Hey sorry i'm confused - how do i fix the issue https://github.com/jellyfin/jellyfin-plugin-pushbullet/issues/5 - what needs to be done?

2020-04-21 21:47 UTC, JustAMan requested changes

2020-04-21 21:47 UTC, JustAMan commented on build.yaml
> +version: "3"
```suggestion
version: "4"
```

As version 3 was already released.

2020-04-29 15:37 UTC, JustAMan approved these changes

2020-04-29 15:37 UTC, merged